-- Kindred Events sample database. Every organisation and event below is fictional.
-- Times are stored as UTC DATETIME values. Seed dates are relative to the UTC
-- import date so that a fresh installation contains upcoming demonstrations.
-- Safe to re-run against an existing installation: fixed IDs are not overwritten.
CREATE DATABASE IF NOT EXISTS charityevents_db
  CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE charityevents_db;

CREATE TABLE IF NOT EXISTS categories (
  id INT UNSIGNED NOT NULL,
  name VARCHAR(60) NOT NULL,
  description VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_categories_name (name)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS events (
  id INT UNSIGNED NOT NULL,
  category_id INT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  starts_at DATETIME NOT NULL COMMENT 'UTC',
  ends_at DATETIME NOT NULL COMMENT 'UTC',
  venue VARCHAR(120) NOT NULL,
  city VARCHAR(80) NOT NULL,
  purpose VARCHAR(220) NOT NULL,
  description TEXT NOT NULL,
  ticket_price DECIMAL(9,2) NOT NULL DEFAULT 0,
  fundraising_goal DECIMAL(11,2) NOT NULL,
  amount_raised DECIMAL(11,2) NOT NULL DEFAULT 0,
  status ENUM('active', 'draft', 'cancelled') NOT NULL DEFAULT 'active',
  image_path VARCHAR(180) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_events_status_time (status, ends_at, starts_at),
  KEY idx_events_category (category_id),
  KEY idx_events_city (city),
  CONSTRAINT fk_events_category FOREIGN KEY (category_id)
    REFERENCES categories (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT chk_event_times CHECK (ends_at > starts_at),
  CONSTRAINT chk_event_money CHECK (ticket_price >= 0 AND fundraising_goal > 0 AND amount_raised >= 0)
) ENGINE=InnoDB;

INSERT IGNORE INTO categories (id, name, description) VALUES
  (1, 'Environment', 'Hands-on projects that restore and protect local places.'),
  (2, 'Education', 'Community learning and access to books, tools and mentoring.'),
  (3, 'Community', 'Neighbour-led events that support everyday wellbeing.'),
  (4, 'Arts & Culture', 'Creative gatherings that make culture accessible.'),
  (5, 'Health & Wellness', 'Movement and wellbeing events for a good cause.');

INSERT IGNORE INTO events (
  id, category_id, name, starts_at, ends_at, venue, city, purpose,
  description, ticket_price, fundraising_goal, amount_raised, status, image_path
) VALUES
  (1, 1, 'Riverbank Planting Day',
    TIMESTAMP(UTC_DATE() + INTERVAL 14 DAY, '00:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 14 DAY, '04:00:00'),
    'Marlow River Reserve', 'Brisbane',
    'Support native habitat restoration along a fictional local waterway.',
    'Join the fictional Riverkind Collective for a morning of native planting, mulch spreading and waterway care. Tools, gloves and a short safety briefing are provided. Funds raised support the collective''s next community planting day. All ages are welcome; children must attend with an adult.',
    0.00, 5000.00, 1860.00, 'active', '/assets/riverbank-planting.svg'),
  (2, 2, 'Lantern Library Book Drive',
    TIMESTAMP(UTC_DATE() + INTERVAL 21 DAY, '01:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 21 DAY, '06:00:00'),
    'Hearth Hall', 'Gold Coast',
    'Build small reading corners for families in need.',
    'Browse donated books, hear volunteer readings and help pack take-home story bundles at this fictional community book drive. Donations support shelves, books and literacy materials distributed by the imaginary Lantern Library Project.',
    5.00, 3200.00, 940.00, 'active', '/assets/lantern-library.svg'),
  (3, 1, 'Coastal Cleanup Morning',
    TIMESTAMP(UTC_DATE() + INTERVAL 28 DAY, '22:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 29 DAY, '02:00:00'),
    'Southpoint Foreshore', 'Sunshine Coast',
    'Remove litter before it reaches coastal wildlife habitats.',
    'The fictional Tide & Thread group leads small teams along an accessible foreshore route. Volunteers receive bags, gloves and a sorting guide. A contribution is optional; collected funds purchase reusable cleanup equipment for future visits.',
    0.00, 4200.00, 1715.00, 'active', '/assets/coastal-cleanup.svg'),
  (4, 3, 'Makers for Neighbours Market',
    TIMESTAMP(UTC_DATE() + INTERVAL 35 DAY, '00:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 35 DAY, '07:00:00'),
    'Willow Commons', 'Brisbane',
    'Fund practical neighbourhood support through a community market.',
    'Meet local makers, try short craft sessions and enjoy a relaxed family market hosted by the fictional Neighbourworks Circle. Stall fees and ticket income support pantry supplies and community connection sessions.',
    8.00, 6500.00, 2330.00, 'active', '/assets/makers-market.svg'),
  (5, 5, 'Sunrise Steps Fun Run',
    TIMESTAMP(UTC_DATE() + INTERVAL 42 DAY, '20:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 42 DAY, '23:30:00'),
    'Banksia Park Oval', 'Toowoomba',
    'Help fund inclusive outdoor activity sessions.',
    'Walk or run a fictional five-kilometre park course at your own pace. Volunteers mark the route and provide water stations. Registration supports inclusive movement classes run by the imaginary Open Path Initiative.',
    18.00, 8000.00, 3120.00, 'active', '/assets/sunrise-run.svg'),
  (6, 3, 'Community Kitchen Table',
    TIMESTAMP(UTC_DATE() + INTERVAL 49 DAY, '07:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 49 DAY, '11:00:00'),
    'Maple Street Hub', 'Ipswich',
    'Share a meal and support community food programs.',
    'Cook alongside volunteers, learn a low-cost seasonal recipe and share a communal supper. The fictional Table Together team uses proceeds for pantry ingredients and future cooking sessions. Vegetarian options are available.',
    12.00, 4500.00, 2085.00, 'active', '/assets/community-kitchen.svg'),
  (7, 2, 'Storybook Festival',
    TIMESTAMP(UTC_DATE() + INTERVAL 56 DAY, '00:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 57 DAY, '05:00:00'),
    'Paperbird Pavilion', 'Brisbane',
    'Bring storytelling workshops to young readers.',
    'A two-day fictional festival of readings, illustration workshops and story games for families. Activities are designed for different ages. Ticket proceeds support free school holiday workshops organised by the imaginary Paperbird Learning Fund.',
    10.00, 7000.00, 3560.00, 'active', '/assets/storybook-festival.svg'),
  (8, 4, 'Reef Colours Art Auction',
    TIMESTAMP(UTC_DATE() + INTERVAL 63 DAY, '08:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 63 DAY, '12:00:00'),
    'Coral Room Gallery', 'Cairns',
    'Support community marine education through local art.',
    'See sea-inspired work from fictional artists, meet the makers and bid in a small silent auction. The invented Blue Current Studio directs proceeds to hands-on marine learning activities for young people.',
    15.00, 9500.00, 4225.00, 'active', '/assets/reef-art-auction.svg'),
  (9, 4, 'Youth Music Night',
    TIMESTAMP(UTC_DATE() + INTERVAL 70 DAY, '08:30:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 70 DAY, '12:30:00'),
    'Northlight Theatre', 'Gold Coast',
    'Help young performers access instruments and rehearsal space.',
    'Enjoy an evening of original music from fictional emerging acts. The imaginary Northlight Youth Arts group hosts the event and applies ticket proceeds to loan instruments and supervised rehearsal sessions.',
    20.00, 6000.00, 2670.00, 'active', '/assets/youth-music-night.svg'),
  (10, 1, 'Urban Garden Workshop',
    TIMESTAMP(UTC_DATE() + INTERVAL 77 DAY, '00:30:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 77 DAY, '04:30:00'),
    'Seedhouse Courtyard', 'Logan',
    'Grow shared garden spaces and practical gardening skills.',
    'Build a small planter and learn about soil, water-saving and edible plants with the fictional Seedhouse Neighbours. Materials are included. Proceeds help maintain a shared garden and free beginner workshops.',
    14.00, 3800.00, 1360.00, 'active', '/assets/urban-garden.svg'),
  (11, 3, 'Planning Session (unpublished)',
    TIMESTAMP(UTC_DATE() + INTERVAL 84 DAY, '00:00:00'),
    TIMESTAMP(UTC_DATE() + INTERVAL 84 DAY, '02:00:00'),
    'Private venue', 'Brisbane',
    'Internal draft to demonstrate publication filtering.',
    'This fictional event is deliberately unpublished and must never appear in the public API.',
    0.00, 1000.00, 0.00, 'draft', '/assets/makers-market.svg');
